unbind r

bind r source-file ~/.tmux.conf

set -g prefix C-s

set -gw mode-keys vi
set -g extended-keys on
set -g extended-keys-format csi-u

set-option -s set-clipboard on
set-option -gu terminal-features
set-option -as terminal-features ',xterm-kitty:clipboard'
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'dracula/tmux'

set -g @resurrect-strategy-nvim 'session'
set -g @continuum-restore 'on'
set -g @dracula-battery-colors "pink dark_gray"
set -g @dracula-cpu-usage-colors "orange dark_gray"
set -g @dracula-git-colors "green dark_gray"
set -g @dracula-ram-usage-colors "cyan dark_gray"
set -g @dracula-time-colors "dark_purple white"
set -g @dracula-plugins "cpu-usage battery ram-usage git time"
set -g @dracula-show-powerline true
set -g @dracula-show-left-icon "#h | #S"
set -g @dracula-battery-label "🦇"
run '~/.tmux/plugins/tpm/tpm'

