-- ~/.config/nvim/lua/plugins/lspconfig.lua

return {

  -- "neovim/nvim-lspconfig",
  --
  -- dependencies = {
  --   { "mason-org/mason.nvim", opts = {} },
  --   "mason-org/mason-lspconfig.nvim",
  --   "WhoIsSethDaniel/mason-tool-installer.nvim",
  --   { "j-hui/fidget.nvim", opts = {} },
  -- },
  --
  -- config = function()
  --   -------------------------------------------------
  --   -- LSP attach keymaps
  --   -------------------------------------------------
  --   vim.api.nvim_create_autocmd("LspAttach", {
  --     group = vim.api.nvim_create_augroup("user-lsp-attach", { clear = true }),
  --
  --     callback = function(event)
  --       local client = vim.lsp.get_client_by_id(event.data.client_id)
  --       if not client then
  --         return
  --       end
  --
  --       -- rustaceanvim が管理
  --       if client.name == "rust_analyzer" or client.name == "rust-analyzer" then
  --         return
  --       end
  --
  --       -------------------------------------------------
  --       -- gopls organize imports
  --       -------------------------------------------------
  --       if client.name == "gopls" then
  --         vim.api.nvim_create_autocmd("BufWritePre", {
  --           buffer = event.buf,
  --           callback = function()
  --             local params = vim.lsp.util.make_range_params()
  --             params.context = { only = { "source.organizeImports" } }
  --
  --             local result = vim.lsp.buf_request_sync(0, "textDocument/codeAction", params, 1000)
  --
  --             for _, res in pairs(result or {}) do
  --               for _, r in pairs(res.result or {}) do
  --                 if r.edit then
  --                   vim.lsp.util.apply_workspace_edit(r.edit, client.offset_encoding)
  --                 else
  --                   vim.lsp.buf.execute_command(r.command)
  --                 end
  --               end
  --             end
  --           end,
  --         })
  --       end
  --
  --       -------------------------------------------------
  --       -- Ruff hover disable
  --       -------------------------------------------------
  --       if client.name == "ruff" then
  --         client.server_capabilities.hoverProvider = false
  --       end
  --
  --       -------------------------------------------------
  --       -- keymaps
  --       -------------------------------------------------
  --       local map = function(keys, func, desc, mode)
  --         mode = mode or "n"
  --         vim.keymap.set(mode, keys, func, { buffer = event.buf, desc = "LSP: " .. desc })
  --       end
  --
  --       map("grn", vim.lsp.buf.rename, "Rename")
  --
  --       map("gra", vim.lsp.buf.code_action, "Code Action", { "n", "x" })
  --       map("grr", require("telescope.builtin").lsp_references, "References")
  --       map("gri", require("telescope.builtin").lsp_implementations, "Implementation")
  --       map("grd", require("telescope.builtin").lsp_definitions, "Definition")
  --       map("grD", vim.lsp.buf.declaration, "Declaration")
  --       map("gO", require("telescope.builtin").lsp_document_symbols, "Symbols")
  --       map("K", vim.lsp.buf.hover, "Hover")
  --     end,
  --   })
  --
  --   -------------------------------------------------
  --   -- diagnostics
  --   -------------------------------------------------
  --   vim.diagnostic.config({
  --     severity_sort = true,
  --
  --     float = {
  --       border = "rounded",
  --       source = "if_many",
  --     },
  --
  --     underline = {
  --       severity = vim.diagnostic.severity.ERROR,
  --     },
  --
  --     virtual_text = true,
  --
  --     signs = {
  --       text = {
  --         [vim.diagnostic.severity.ERROR] = "󰅚 ",
  --         [vim.diagnostic.severity.WARN] = "󰀪 ",
  --         [vim.diagnostic.severity.INFO] = "󰋽 ",
  --         [vim.diagnostic.severity.HINT] = "󰌶 ",
  --       },
  --     },
  --   })
  --
  --   -------------------------------------------------
  --   -- ddc LSP capabilities
  --   -------------------------------------------------
  --   local capabilities = vim.tbl_deep_extend(
  --     "force",
  --     vim.lsp.protocol.make_client_capabilities(),
  --     require("ddc_source_lsp").make_client_capabilities()
  --   )
  --
  --   -------------------------------------------------
  --   -- LSP server settings
  --   -------------------------------------------------
  --   local servers = {
  --
  --     -------------------------------------------------
  --     -- Lua
  --     -------------------------------------------------
  --     lua_ls = {
  --       settings = {
  --         Lua = {
  --
  --           completion = {
  --             callSnippet = "Replace",
  --           },
  --
  --           diagnostics = {
  --             globals = { "vim" },
  --           },
  --
  --           workspace = {
  --             checkThirdParty = false,
  --           },
  --
  --           hint = {
  --             enable = true,
  --           },
  --
  --           telemetry = {
  --             enable = false,
  --           },
  --         },
  --       },
  --
  --       -------------------------------------------------
  --       -- Go
  --       -------------------------------------------------
  --       gopls = {
  --         settings = {
  --           gopls = {
  --             gofumpt = true,
  --
  --             analyses = {
  --               unusedparams = true,
  --               nilness = true,
  --               unusedwrite = true,
  --               useany = true,
  --             },
  --
  --             hints = {
  --               assignVariableTypes = true,
  --               parameterNames = true,
  --               compositeLiteralFields = true,
  --               compositeLiteralTypes = true,
  --             },
  --
  --             staticcheck = true,
  --             semanticTokens = true,
  --           },
  --         },
  --       },
  --
  --       -------------------------------------------------
  --       -- Python
  --       -------------------------------------------------
  --       basedpyright = {
  --         settings = {
  --           basedpyright = {
  --             analysis = {
  --               typeCheckingMode = "basic",
  --               autoSearchPaths = true,
  --               useLibraryCodeForTypes = true,
  --             },
  --           },
  --         },
  --       },
  --
  --       ruff = {
  --         on_attach = function(client)
  --           client.server_capabilities.hoverProvider = false
  --         end,
  --       },
  --
  --       -------------------------------------------------
  --       -- OCaml
  --       -------------------------------------------------
  --       ocamllsp = {},
  --     },
  --   }
  --
  --   -------------------------------------------------
  --   -- Mason LSP install
  --   -------------------------------------------------
  --   local lsp_servers = vim.tbl_keys(servers)
  --
  --   require("mason-lspconfig").setup({
  --     ensure_installed = lsp_servers,
  --
  --     automatic_installation = {
  --       exclude = { "rust_analyzer", "ocamllsp" },
  --     },
  --
  --     handlers = {
  --       function(server_name)
  --         if server_name == "rust_analyzer" then
  --           return
  --         end
  --
  --         local config = servers[server_name] or {}
  --
  --         config.capabilities =
  --           vim.tbl_deep_extend("force", capabilities, config.capabilities or {})
  --
  --         require("lspconfig")[server_name].setup(config)
  --       end,
  --     },
  --   })
  --
  --   -------------------------------------------------
  --   -- Mason tool installer (formatter / cli tools)
  --   -------------------------------------------------
  --   require("mason-tool-installer").setup({
  --     ensure_installed = {
  --
  --       -- formatters
  --       "stylua",
  --       "prettier",
  --
  --       -- go tools
  --       "goimports",
  --       "gofumpt",
  --       "gomodifytags",
  --       "impl",
  --       "delve",
  --       "golangci-lint",
  --     },
  --   })
  --
  --   -------------------------------------------------
  --   -- OCaml (opam 管理)
  --   -------------------------------------------------
  --   vim.lsp.config("ocamllsp", {
  --     capabilities = capabilities,
  --   })
  --
  --   vim.lsp.enable("ocamllsp")
  -- end,
}
